// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function post(user, taskName) {
  var exit = 0;
  switch (user.tag | 0) {
    case 0 : 
    case 1 : 
        exit = 1;
        break;
    case 2 : 
        return undefined;
    
  }
  if (exit === 1) {
    return /* Task */[/* record */[
              /* name : TaskName */[taskName],
              /* userId */user[0][0][/* id */0]
            ]];
  }
  
}

var poster = /* Poster */Block.__(1, [/* UserAttr */[/* record */[/* id : UserId */["123"]]]]);

function postWithUser(param) {
  return post(poster, param);
}

var job = postWithUser("cleaning");

exports.post = post;
exports.poster = poster;
exports.postWithUser = postWithUser;
exports.job = job;
/* job Not a pure module */
